"""initial schema

Revision ID: 22dc55fec28c
Revises: 
Create Date: 2026-01-24 21:39:22.858050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dc55fec28c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('observed_pressure', sa.Float(), nullable=False),
    sa.Column('predicted_pressure', sa.Float(), nullable=False),
    sa.Column('absolute_error', sa.Float(), nullable=False),
    sa.Column('squared_error', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_errors_forecast_id'), 'forecast_errors', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecast_errors_hospital_id'), 'forecast_errors', ['hospital_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('predicted_pressure', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_hospital_id'), 'forecasts', ['hospital_id'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('permit_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_permit_id'), 'hospitals', ['permit_id'], unique=True)
    op.create_index(op.f('ix_hospitals_region'), 'hospitals', ['region'], unique=False)
    op.create_table('er_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('functional_stretchers', sa.Integer(), nullable=False),
    sa.Column('occupied_stretchers', sa.Integer(), nullable=False),
    sa.Column('patients_total', sa.Integer(), nullable=False),
    sa.Column('patients_waiting_mc', sa.Integer(), nullable=False),
    sa.Column('patients_over_24h', sa.Integer(), nullable=False),
    sa.Column('patients_over_48h', sa.Integer(), nullable=False),
    sa.Column('avg_stay_stretcher', sa.Float(), nullable=True),
    sa.Column('avg_stay_ambulatory', sa.Float(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_er_snapshots_hospital_id'), 'er_snapshots', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_er_snapshots_hospital_id'), table_name='er_snapshots')
    op.drop_table('er_snapshots')
    op.drop_index(op.f('ix_hospitals_region'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_permit_id'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_forecasts_hospital_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_forecast_errors_hospital_id'), table_name='forecast_errors')
    op.drop_index(op.f('ix_forecast_errors_forecast_id'), table_name='forecast_errors')
    op.drop_table('forecast_errors')
    # ### end Alembic commands ###
