"""add unique constraint to er_snapshots

Revision ID: 62b13d92d07f
Revises: 22dc55fec28c
Create Date: 2026-01-27 22:47:56.685085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b13d92d07f'
down_revision: Union[str, Sequence[str], None] = '22dc55fec28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_er_snapshot_hospital_time', 'er_snapshots', ['hospital_id', 'snapshot_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_er_snapshot_hospital_time', 'er_snapshots', type_='unique')
    # ### end Alembic commands ###
