"""rename published_at to updated_at

Revision ID: 89a568e54248
Revises: 62b13d92d07f
Create Date: 2026-01-28 00:22:57.938784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a568e54248'
down_revision: Union[str, Sequence[str], None] = '62b13d92d07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('er_snapshots', 'published_at', new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('er_snapshots', 'updated_at', new_column_name='published_at')
    # ### end Alembic commands ###
