"""review feedback table

Revision ID: b421960f39bb
Revises: c52042a7a9dc
Create Date: 2026-02-25 04:26:39.663493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b421960f39bb'
down_revision: Union[str, Sequence[str], None] = 'c52042a7a9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('thumbs', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_column('feedback', 'thumbs')
    # ### end Alembic commands ###
