"""remove pressure_score from er_snapshots

Revision ID: cae7a0fa3017
Revises: fc911f7ecc55
Create Date: 2026-01-28 22:31:51.743765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae7a0fa3017'
down_revision: Union[str, Sequence[str], None] = 'fc911f7ecc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_er_snapshots_pressure_score'), table_name='er_snapshots')
    op.drop_column('er_snapshots', 'pressure_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('er_snapshots', sa.Column('pressure_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_er_snapshots_pressure_score'), 'er_snapshots', ['pressure_score'], unique=False)
    # ### end Alembic commands ###
