"""add horizon_hours and forecast_time  to forecast error

Revision ID: cf70a6e4621a
Revises: faa4073079fd
Create Date: 2026-02-13 16:57:26.686180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf70a6e4621a'
down_revision: Union[str, Sequence[str], None] = 'faa4073079fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_errors', sa.Column('horizon_hours', sa.Integer(), nullable=False))
    op.add_column('forecast_errors', sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_errors', 'forecast_time')
    op.drop_column('forecast_errors', 'horizon_hours')
    # ### end Alembic commands ###
