"""add risk_level to forecast table

Revision ID: d1d7a4c451d3
Revises: cae7a0fa3017
Create Date: 2026-01-31 15:20:07.599241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d7a4c451d3'
down_revision: Union[str, Sequence[str], None] = 'cae7a0fa3017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('risk_level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'risk_level')
    # ### end Alembic commands ###
