"""add evaluated to forecast

Revision ID: faa4073079fd
Revises: d1d7a4c451d3
Create Date: 2026-02-04 23:50:41.898058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa4073079fd'
down_revision: Union[str, Sequence[str], None] = 'd1d7a4c451d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('evaluated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'evaluated')
    # ### end Alembic commands ###
